### ISSUE TITLE
build-vue.js无法正常执行

### ISSUE THREAD

**Issue by asins** [lyon007/VueJS-docset-CN#2]
执行后会报错，没有使用过sqlite.js，不知具体错在哪里呢，

```sh
~/Documents/VueJS-docset-CN master*
❯ node build-vue.js
/Users/asins/Documents/VueJS-docset-CN/node_modules/sqlite-sync/sqlite.js:79
			throw x;
			^

TypeError: SQL.Database is not a constructor
    at sqlite.connect (/Users/asins/Documents/VueJS-docset-CN/node_modules/sqlite-sync/sqlite.js:76:14)
    at createIndexSqlite (/Users/asins/Documents/VueJS-docset-CN/build-vue.js:87:8)
    at Object.<anonymous> (/Users/asins/Documents/VueJS-docset-CN/build-vue.js:46:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by lyon007** [comment]
抱歉啊，之前没啥时间来看。我看了一下，没什么问题啊，是不是你包没有下全？
